name: calendar_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  intl: ^0.18.1

  # pik file
  file_picker: ^6.1.1

  # image picker
  image_picker: ^1.0.4

  # open file
  open_file: ^3.3.2

  # calendar
  calendar_view:
    path: ./calender_view

  # for localization
  flutter_localizations:
    sdk: flutter

  # Firebase
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  firebase_core: ^2.21.0

  # google sign in
  google_sign_in: ^6.1.5
  firebase_auth: ^4.12.1

  # for loading gif
  lottie: ^2.7.0

  # for pdf view
  syncfusion_flutter_pdfviewer: ^23.2.4
  http: ^1.1.0
  url_launcher: ^6.2.1

dev_dependencies:

  build_runner:
  flutter_gen_runner:
  # injectable_generator:

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/temp/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
