import 'package:calendar_app/components/buttonItem/button_item.dart';
import 'package:calendar_app/constants/app_strings.dart';
import 'package:calendar_app/extensions/buildcontext_ext.dart';
import 'package:calendar_app/extensions/date_time_ext.dart';
import 'package:calendar_app/gen/assets.gen.dart';
import 'package:calendar_app/core/base_provider.dart';
import 'package:calendar_app/screens/addCalendarData/add_calendar_data.dart';
import 'package:calendar_app/screens/addCalendarData/arguments.dart';
import 'package:calendar_app/screens/calendar/widgets/info_dialog.dart';
import 'package:calendar_app/services/preference_helper/pref_service.dart';
import 'package:calendar_app/utils/commonButton/common_button.dart';
import 'package:calendar_view/calendar_view.dart';
import 'package:flutter/material.dart';
import 'package:gap/gap.dart';
import 'package:provider/provider.dart';

part 'calendar_provider.dart';
part 'calendar_ui.dart';
part 'widgets/date_details_dialog.dart';
